spring.application.name=order-api

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# H2 Console Configuration (IDE may show unknown property warning, but it works)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# allow springdoc to bypass security
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true