spring.application.name=inventory-service
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# use String deserializer for both key and value
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# ↑ receive raw JSON string — parse manually in the listener